<h1 style="color:blue;text-align:center;">NumPy Playground</h1>

<h2>Imports</h2>

In [12]:
import numpy as np

<h2>Create</h2>

In [157]:
# Will create a random array with comma seperated parameters representing the number of indexes in each dimensions of the array.
# An additional parameter will add an additional dimension.

floatData = np.random.rand(3,2)
floatData

array([[0.72319549, 0.39502007],
       [0.13944012, 0.0719303 ],
       [0.65223496, 0.36249108]])

In [158]:
# Different data types have differnet way of specificying the number of dimensions which is a little tilting.
intData = np.random.randint(10, size=(3,2))
intData

array([[8, 9],
       [3, 0],
       [2, 5]])

In [159]:
# The shape is the first parameter as a tuple.
zeroes = np.zeros((1, 2), dtype=int)
zeroes

array([[0, 0]])

In [160]:
# The shape is the first parameter as a tuple.
full = np.full((2, 3), 7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [164]:
# The shape is the first parameter as a tuple.
ones = np.ones((2,2,2), dtype=int)
ones

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [169]:
# You can initialise your own array.
initArray = np.array([2,3,4])
print(initArray)

[2 3 4]


<h2>Read</h2>

In [197]:
# Data for following sections
data = np.random.rand(3,3)
data

array([[0.88496695, 0.62237958, 0.90540177],
       [0.93888906, 0.44437996, 0.95256602],
       [0.27455452, 0.38366212, 0.58124431]])

In [201]:
# Shape attribute
shape = data.shape
shape

(3, 3)

In [200]:
# Size Attribute - Total number of elements of the base type across all arrays dimensions (.count)
size = data.size
size

9

In [199]:
# Type Attribute
types = data.dtype
types

dtype('float64')

In [202]:
# Accessing a value at index
value = data[0]
value

array([0.88496695, 0.62237958, 0.90540177])

In [206]:
# Get a range of indicides (up to but not including the value on the right)
# Index 0 and 1
range = data[0:2]
range

array([[0.88496695, 0.62237958, 0.90540177],
       [0.93888906, 0.44437996, 0.95256602]])

In [212]:
# Negative starts from the end and moves across (it has to be -1 or less as you can't have -0)
reverse = data[-1][-1]
reverse

0.5812443086465364

<h2>Update</h2>

In [215]:
list1 = np.random.rand(10)
list1

array([0.60021367, 0.34299665, 0.62456557, 0.22983874, 0.24308194,
       0.08846441, 0.75680419, 0.90391667, 0.57758502, 0.83688457])

In [221]:
list2 = np.random.rand(10)
list2

array([0.46115952, 0.24956138, 0.45952247, 0.89754979, 0.11398792,
       0.8795637 , 0.28503448, 0.034935  , 0.97359249, 0.41088379])

In [223]:
# Add - The shape must be equal
add = np.add(list1, list2)
add

array([1.06137319, 0.59255803, 1.08408804, 1.12738853, 0.35706987,
       0.96802811, 1.04183867, 0.93885168, 1.5511775 , 1.24776837])

In [226]:
# Subtract - The shape must be equal
subtract = np.subtract(list1, list2)
subtract

array([ 0.13905416,  0.09343527,  0.1650431 , -0.66771106,  0.12909402,
       -0.79109928,  0.47176972,  0.86898167, -0.39600747,  0.42600078])

In [229]:
# Multiple - The shape must be equal
multiply = np.multiply(list1, list2)
multiply

array([0.27679425, 0.08559872, 0.28700191, 0.20629171, 0.02770841,
       0.07781009, 0.21571529, 0.03157833, 0.56233243, 0.34386231])

In [230]:
# Divide - The shape must be equal
divide = np.divide(list1, list2)
divide

array([ 1.30153158,  1.37439795,  1.35916219,  0.25607352,  2.13252367,
        0.10057761,  2.65513213, 25.87424117,  0.59325131,  2.03679139])

In [232]:
# Dot - (a1b1 + a2b2 ... anbn)
dot = np.dot(list1, list2)
dot

2.1146934406419606

In [234]:
# SAPLEMM - Suggested way to remember the statistical method

In [235]:
sqrRoot = np.sqrt(25)
sqrRoot

5.0

In [236]:
# Absolute
absolute = np.abs(-2)
absolute

2

In [237]:
# Power
power = np.power(2, 3)
power

8

In [246]:
# log 
log = np.log10(100)
log

2.0

In [248]:
exp = np.exp([3,2])
exp

array([20.08553692,  7.3890561 ])

In [250]:
min = np.min(list1)
min

0.08846441474494471

In [254]:
max = np.max(list1)
max

0.9039166731925476

In [258]:
# Updating a value
data[0][0] = 100
data

array([[100.        ,   0.62237958,   0.90540177],
       [  0.93888906,   0.44437996,   0.95256602],
       [  0.27455452,   0.38366212,   0.58124431]])

In [261]:
# Sorting
data.sort()
data

array([[  0.62237958,   0.90540177, 100.        ],
       [  0.44437996,   0.93888906,   0.95256602],
       [  0.27455452,   0.38366212,   0.58124431]])

In [265]:
# Appending
data = np.append(data, [500, 500])
data

array([6.22379577e-01, 9.05401766e-01, 1.00000000e+02, 4.44379958e-01,
       9.38889058e-01, 9.52566016e-01, 2.74554519e-01, 3.83662120e-01,
       5.81244309e-01, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 5.00000000e+02, 5.00000000e+02, 5.00000000e+02,
       5.00000000e+02])

In [267]:
# Insert
data = np.insert(data, 0, 900)
data

array([9.00000000e+02, 9.00000000e+02, 6.22379577e-01, 9.05401766e-01,
       1.00000000e+02, 4.44379958e-01, 9.38889058e-01, 9.52566016e-01,
       2.74554519e-01, 3.83662120e-01, 5.81244309e-01, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 5.00000000e+02,
       5.00000000e+02, 5.00000000e+02, 5.00000000e+02])

<h2>Delete</h2>

In [270]:
anyArray = np.random.rand(5,5,2)
anyArray

array([[[0.35253154, 0.74681324],
        [0.67139594, 0.78821017],
        [0.49799985, 0.09970005],
        [0.677165  , 0.36885184],
        [0.75575336, 0.16273419]],

       [[0.16966685, 0.76690817],
        [0.68527226, 0.5316314 ],
        [0.49505123, 0.49134671],
        [0.0796984 , 0.56396864],
        [0.96807573, 0.12827742]],

       [[0.362001  , 0.79544927],
        [0.2128533 , 0.9614521 ],
        [0.29737016, 0.35067423],
        [0.56234977, 0.34027417],
        [0.05662399, 0.47637933]],

       [[0.49775483, 0.59102266],
        [0.99061465, 0.90902119],
        [0.94762893, 0.06078625],
        [0.80005583, 0.8613111 ],
        [0.84117842, 0.27014171]],

       [[0.72988583, 0.39904536],
        [0.44417802, 0.61545773],
        [0.26481397, 0.39350946],
        [0.47634533, 0.57830068],
        [0.91891556, 0.52744863]]])

In [272]:
np.delete(anyArray, 0, axis=1)

array([[[0.67139594, 0.78821017],
        [0.49799985, 0.09970005],
        [0.677165  , 0.36885184],
        [0.75575336, 0.16273419]],

       [[0.68527226, 0.5316314 ],
        [0.49505123, 0.49134671],
        [0.0796984 , 0.56396864],
        [0.96807573, 0.12827742]],

       [[0.2128533 , 0.9614521 ],
        [0.29737016, 0.35067423],
        [0.56234977, 0.34027417],
        [0.05662399, 0.47637933]],

       [[0.99061465, 0.90902119],
        [0.94762893, 0.06078625],
        [0.80005583, 0.8613111 ],
        [0.84117842, 0.27014171]],

       [[0.44417802, 0.61545773],
        [0.26481397, 0.39350946],
        [0.47634533, 0.57830068],
        [0.91891556, 0.52744863]]])

<h2>File Management</h2>

In [275]:
# Save to current directory
np.save('Any Array', anyArray)

In [277]:
# Load from current directory
loaded = np.load('Any Array.npy')
loaded

array([[[0.35253154, 0.74681324],
        [0.67139594, 0.78821017],
        [0.49799985, 0.09970005],
        [0.677165  , 0.36885184],
        [0.75575336, 0.16273419]],

       [[0.16966685, 0.76690817],
        [0.68527226, 0.5316314 ],
        [0.49505123, 0.49134671],
        [0.0796984 , 0.56396864],
        [0.96807573, 0.12827742]],

       [[0.362001  , 0.79544927],
        [0.2128533 , 0.9614521 ],
        [0.29737016, 0.35067423],
        [0.56234977, 0.34027417],
        [0.05662399, 0.47637933]],

       [[0.49775483, 0.59102266],
        [0.99061465, 0.90902119],
        [0.94762893, 0.06078625],
        [0.80005583, 0.8613111 ],
        [0.84117842, 0.27014171]],

       [[0.72988583, 0.39904536],
        [0.44417802, 0.61545773],
        [0.26481397, 0.39350946],
        [0.47634533, 0.57830068],
        [0.91891556, 0.52744863]]])