<h1 style="color:blue;text-align:center;">NumPy Playground</h1>

<h2>Imports</h2>

In [12]:
import numpy as np

<h2>Create</h2>

In [157]:
# Will create a random array with comma seperated parameters representing the number of indexes in each dimensions of the array.
# An additional parameter will add an additional dimension.

floatData = np.random.rand(3,2)
floatData

array([[0.72319549, 0.39502007],
       [0.13944012, 0.0719303 ],
       [0.65223496, 0.36249108]])

In [158]:
# Different data types have differnet way of specificying the number of dimensions which is a little tilting.
intData = np.random.randint(10, size=(3,2))
intData

array([[8, 9],
       [3, 0],
       [2, 5]])

In [159]:
# The shape is the first parameter as a tuple.
zeroes = np.zeros((1, 2), dtype=int)
zeroes

array([[0, 0]])

In [160]:
# The shape is the first parameter as a tuple.
full = np.full((2, 3), 7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [164]:
# The shape is the first parameter as a tuple.
ones = np.ones((2,2,2), dtype=int)
ones

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [165]:

initArray = np.array([2,3,4])
print(initArray)

[2 3 4]
